services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true  # Permet le hot reload sur certains systèmes
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/processors:/app/processors  # Assure que le dossier processors est correctement monté
      - ./uploaded_files:/app/uploaded_files
    environment:
      - WEAVIATE_URL=
      - WEAVIATE_API_KEY=
      - EMBEDDER_API_KEY=
      - EMBEDDER_MODEL=voyagerai
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app  # Aide Python à trouver les modules
    restart: unless-stopped

  # Weaviate peut être ajouté ici si vous souhaitez exécuter une instance locale
  # weaviate:
  #   image: semitechnologies/weaviate:1.19.6
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     QUERY_DEFAULTS_LIMIT: 25
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
  #     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
  #     DEFAULT_VECTORIZER_MODULE: 'none'
  #   volumes:
  #     - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: